
name: Stylelint Test
on:
  push:
    branches: ['*']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.1.4
        with:
          node-version: '12'

      - uses: actions/cache@v2.1.4
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install Node dependencies
        run: yarn install

      - name: Test
        run: yarn test
